name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build CMake
      run: |
        git submodule update --init --recursive
        cd Core
        mkdir build
        cd build
        cmake .. -A x64
        cmake --build . --config Release
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Altseed2.sln
    - name: Build
      run: dotnet build Altseed2.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Altseed2.sln --no-restore --verbosity normal
