name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build CMake
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        build-dir: Core/build
        build-type: Release
        submodule-update: true
        configure-options: '.. -G "Visual Studio 15 2017" -A x64 -DBUILD_TEST=ON'
        build-options: '. --config Release'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
